### ISSUE TITLE
bug references got "Ticket not found", but they exist

### ISSUE THREAD

**Issue by Soulofdestiny** [okurz/openqa_review#46]
* sles+extratests -> [boo#1011931](https://bugzilla.opensuse.org/show_bug.cgi?id=1011931) (Ticket not found)

**Existing Product bugs:**

* migration_offline_sle12 -> [bsc#1012564](https://bugzilla.suse.com/show_bug.cgi?id=1012564) (Ticket not found)

**Comment by okurz** [comment]
probably fixed with https://github.com/okurz/openqa_review/commit/8239c34199d95fcaf34bafe4640cd60452fb32be
