### ISSUE TITLE
Review contains invalid HTML

### ISSUE THREAD

**Issue by Martchus** [okurz/openqa_review#62]
The review accessible under https://w3.suse.de/~okurz/openqa_suse_de_status.html contains invalid HTML.

```
<p><strong>Arch:</strong> s390x <strong>Status: <font color="green">Green</font></strong> <hr> <strong>Arch:</strong> x86_64 <strong>Status: <font color="green">Green</font></strong></p>
```

There shouldn't be a closing `</p>` according to the validator. This is because the `<hr>` element is not inside the `<p>` element. It causes the `<p>` element to be implicitly closed before and hence the closing `</p>` is wrong.

Also the use of `<font ...` should be avoided.

![spectacle gz7336](https://cloud.githubusercontent.com/assets/10248953/25895215/4dcfb38c-357f-11e7-8357-7f61fc63cb92.png)

This HTML output seems to be used directly and unaltered used in openQA comments causing invalid HTML in openQA.

**Comment by okurz** [comment]
I don't understand how the font-color part could be done better in a portable way. Thanks for the issue reporting. You are welcome to provide a pull request to get accustomed to openqa-review as well :-)

**Comment by Martchus** [comment]
> I don't understand how the font-color part could be done better in a portable way.

```
<span style="color: green;">Green</span>
```

> You are welcome to provide a pull request

I'll do when I'm in the office again.

**Comment by okurz** [comment]
merged. Could you recheck the generated page e.g. tomorrow?

**Comment by Martchus** [comment]
Yes, I can check.

**Comment by Martchus** [comment]
The HTML looks ok now.
