### ISSUE TITLE
add soft-fails without bugref to report instead of log

### ISSUE THREAD

**Issue by okurz** [okurz/openqa_review#76]
## Motivation
In case openqa-review finds a soft-fail reference but without a valid bug reference this is reported in logs but rather should show up in the generated report as this is relevant information for the test reviewers.

## Acceptance criteria
* **AC1:** A soft-fail reference in test without a valid bugref is reported in the generated report
* **AC2:** soft-fail references without valid bugref are not reported as error in log

## Further details

Currently the log messages contain for example the following report:

```
ERROR:openqa_review.openqa_review:Could not find any soft failure reference within details of soft-failed job 'https://openqa.suse.de/tests/1580533'. Could be deleted workaround needle?.
ERROR:openqa_review.openqa_review:Failed to find valid bug tracker URL for {'state': 'NEW_SOFT_ISSUE', 'href': u'/tests/1562126', 'failedmodules': [], 'bugref': u'fate#321208: activating existing encrypted volume does *not* yield an encrypted system if not forcing'} with error u'ate'. Skipping current result
```

**Comment by OleksandrOrlov** [comment]
I've added an appropriate PR: https://github.com/okurz/openqa_review/pull/87
Could you please verify it.

**Comment by okurz** [comment]
fixed with #87, thanks

**Comment by okurz** [comment]
I think we missed something. We still have the line

```python
log.error('Could not find any soft failure reference within details of soft-failed job \'%s\'. Could be deleted workaround needle?.' %
```

and probably should delete it. What do you think?

**Comment by okurz** [comment]
Please also crosscheck the currently generated https://w3.nue.suse.com/~okurz/openqa_suse_de_status.html which mentions https://openqa.suse.de/tests/1753477#step/snapper_rollback/1 which does not seem to have any valid bugref in neither the record_soft_failure nor workaround needle

**Comment by OleksandrOrlov** [comment]
@okurz, in the last report there is no 'snapper_rollback' module. Is it possible to view how the problem looked like? Unfortunately, I was not able to view the issue that day, when you've mentioned it.

**Comment by okurz** [comment]
Just check the daily email you should receive with all the noise :)

**Comment by okurz** [comment]
Another thing I realized: https://w3.nue.suse.com/~okurz/openqa_opensuse_org_status.html mentions https://fate.suse.com/320901 but not as a link but only as text

**Comment by OleksandrOrlov** [comment]
yes, the link is not processed properly. I'll look at this too. Thank you.

**Comment by OleksandrOrlov** [comment]
@okurz , but at the same time, I do not understand why openQA behaves like that in your example. On my local environment it highlights the links and even converts 'progress' links into 'poo#123' format. May the openQA from your example be out-dated?

**Comment by okurz** [comment]
Ok, I am not completely sure but let's assume that with #103 we have everything covered. Thanks.
